name: Deploy-Android-Dev

on:
  push:
    branches:
      - dev

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_ANDROID_ENV_DEV }}
  APP_NAME: ${{ 'someshsomani457.imp-gmail.com/cf_dev' }}
  TESTING_GROUP: ${{ 'cf_dev' }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/dev/release/app-dev-release.apk' }}

jobs:
  codepush:
    name: CODEPUSH
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'codepush') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Codepush Update
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a ${{ env.APP_NAME }}  -d Production
        env:
          APPCENTER_ACCESS_TOKEN: ${{ env.APP_CENTER_TOKEN }}  

  build:
    name: BUILD
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'codepush' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Install dependencies
        run: npm install

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Gradlew permission
        run: cd android && chmod +x ./gradlew

      - name: Build android
        run: cd android && ./gradlew assembleDevRelease

      - name: Upload to app center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
